export const demo4VisualConfig = Object.freeze( {
  placement: Object.freeze( {
    floorY: 0.035,
    overlayLift: 0.018,
    placementSurfaceSize: 4.5,
    defaultPreviewPosition: Object.freeze( [ 0, 0.053, - 1.45 ] ),
    defaultPreviewQuaternion: Object.freeze( [ 0, 0, 0, 1 ] ),
    defaultScale: 1,
    driver: 'left-controller',
    fallbackControllerSource: 'controller-0',
    hitTestSmoothingAlpha: 0.18,
    hitTestRotationSmoothingAlpha: 0.18,
    maxFrameJumpMeters: 0.25,
    maxSurfaceTiltDeg: 35,
    requiredStableFrames: 3,
    staleHitHoldMs: 250,
  } ),
  overlay: Object.freeze( {
    contentYawOffsetRad: Math.PI,
  } ),
  placementInstructionCard: Object.freeze( {
    width: 0.82,
    height: 0.26,
    verticalOffset: 0.48,
    cameraFallbackDistance: 1.05,
    cameraFallbackYOffset: - 0.08,
    positionSmoothingAlpha: 0.22,
    staleHitHoldMs: 300,
    backgroundColor: 0x081018,
    backgroundOpacity: 0.92,
    borderColor: 0x7fe7dc,
    borderOpacity: 0.86,
    renderOrder: 42,
    bodyText: Object.freeze( {
      planeHeight: 0.14,
      fontSize: 34,
      padding: 14,
      fixedWidth: 560,
      maxTextWidth: 520,
      lineHeight: 1.18,
      fontWeight: '800',
      textAlign: 'left',
      textColor: '#f6fbff',
      backgroundColor: 'rgba(8, 16, 24, 0)',
      borderWidth: 0,
    } ),
    statusText: Object.freeze( {
      planeHeight: 0.065,
      fontSize: 25,
      padding: 10,
      fixedWidth: 560,
      maxTextWidth: 520,
      lineHeight: 1.12,
      fontWeight: '700',
      textAlign: 'left',
      textColor: '#9ff3e8',
      backgroundColor: 'rgba(8, 16, 24, 0)',
      borderWidth: 0,
    } ),
  } ),
  footprint: Object.freeze( {
    width: 1.38,
    depth: 0.92,
    baseColor: 0x15353f,
    baseOpacity: 0.34,
    previewColor: 0x7fe7dc,
    previewOpacity: 0.18,
    borderColor: 0xa8fff5,
    borderOpacity: 0.78,
    alertColor: 0xffd58f,
    renderOrder: 4,
  } ),
  markers: Object.freeze( {
    baseRadius: 0.045,
    radiusScale: 0.052,
    minHeight: 0.06,
    maxHeight: 0.38,
    hoverScale: 1.12,
    selectedScale: 1.2,
    hitRadius: 0.12,
    hitHeight: 0.5,
    colors: Object.freeze( {
      occupancy: 0x6cc9ff,
      noise: 0xffc96b,
      co2: 0xc59cff,
    } ),
    emissive: Object.freeze( {
      occupancy: 0x12415c,
      noise: 0x53340c,
      co2: 0x32195c,
    } ),
    hoverColor: 0xf3fbff,
    selectedColor: 0xffffff,
    mutedOpacity: 0.18,
    visibleOpacity: 0.88,
    selectedRingColor: 0xffd58f,
  } ),
  interaction: Object.freeze( {
    dwellDurationMs: 900,
    dwellProgressColor: 0xffffff,
    dwellProgressEmissive: 0x62531c,
    dwellProgressOpacity: 0.92,
    dwellProgressBaseRadius: 0.08,
    dwellProgressRadius: 0.16,
    dwellProgressTubeRadius: 0.006,
  } ),
  text: Object.freeze( {
    label: Object.freeze( {
      worldHeight: 0.09,
      fontSize: 50,
      padding: 12,
      fixedWidth: 180,
      maxTextWidth: 150,
      fontWeight: '700',
      textAlign: 'center',
      textColor: '#f6fbff',
      backgroundColor: 'rgba(6, 12, 18, 0.66)',
      borderColor: 'rgba(255, 213, 143, 0.62)',
      borderWidth: 3,
      borderRadius: 18,
    } ),
    panelTitle: Object.freeze( {
      planeHeight: 0.08,
      fontSize: 46,
      padding: 12,
      fixedWidth: 720,
      maxTextWidth: 680,
      fontWeight: '800',
      textAlign: 'center',
      textColor: '#f6fbff',
      backgroundColor: 'rgba(8, 16, 24, 0)',
      borderWidth: 0,
    } ),
    panelBody: Object.freeze( {
      planeHeight: 0.072,
      fontSize: 29,
      padding: 12,
      fixedWidth: 740,
      maxTextWidth: 704,
      lineHeight: 1.12,
      fontWeight: '600',
      textAlign: 'left',
      textColor: '#dcecff',
      backgroundColor: 'rgba(8, 16, 24, 0)',
      borderWidth: 0,
    } ),
    panelDetail: Object.freeze( {
      planeHeight: 0.092,
      fontSize: 27,
      padding: 12,
      fixedWidth: 740,
      maxTextWidth: 704,
      lineHeight: 1.12,
      fontWeight: '700',
      textAlign: 'left',
      textColor: '#f6fbff',
      backgroundColor: 'rgba(8, 16, 24, 0)',
      borderWidth: 0,
    } ),
    panelHelp: Object.freeze( {
      planeHeight: 0.058,
      fontSize: 24,
      padding: 10,
      fixedWidth: 740,
      maxTextWidth: 704,
      lineHeight: 1.1,
      fontWeight: '600',
      textAlign: 'left',
      textColor: '#b7d7e4',
      backgroundColor: 'rgba(8, 16, 24, 0)',
      borderWidth: 0,
    } ),
    button: Object.freeze( {
      planeHeight: 0.056,
      fontSize: 27,
      padding: 10,
      fixedWidth: 300,
      maxTextWidth: 276,
      fontWeight: '800',
      textAlign: 'center',
      textColor: '#f6fbff',
      backgroundColor: 'rgba(8, 16, 24, 0)',
      borderWidth: 0,
    } ),
  } ),
  panel: Object.freeze( {
    width: 1.24,
    height: 0.88,
    position: Object.freeze( [ 0, 0.9, 0.42 ] ),
    backgroundColor: 0x101924,
    backgroundOpacity: 0.86,
    borderColor: 0x7fe7dc,
    buttonColor: 0x244457,
    buttonHoverColor: 0x386a80,
    buttonActiveColor: 0x4f8fa8,
    buttonDisabledColor: 0x1b2630,
    buttonWidth: 0.32,
    buttonHeight: 0.064,
    textPositions: Object.freeze( {
      title: Object.freeze( [ 0, 0.36 ] ),
      task: Object.freeze( [ 0, 0.28 ] ),
      placement: Object.freeze( [ 0, 0.21 ] ),
      state: Object.freeze( [ 0, 0.14 ] ),
      detail: Object.freeze( [ 0, 0.055 ] ),
      help: Object.freeze( [ 0, - 0.045 ] ),
    } ),
    buttonColumns: Object.freeze( [ - 0.39, 0, 0.39 ] ),
    buttonRows: Object.freeze( {
      metrics: - 0.145,
      times: - 0.225,
      controls: - 0.305,
      actions: - 0.385,
    } ),
  } ),
  supportPedestal: Object.freeze( {
    color: 0xdce3ea,
    opacity: 0.32,
    minVisibleHeight: 0.04,
    label: Object.freeze( {
      text: 'Real-world surface height reference',
      horizontalOffset: 0.16,
      zOffset: 0.08,
      worldHeight: 0.105,
      fontSize: 34,
      padding: 12,
      fixedWidth: 560,
      maxTextWidth: 520,
      lineHeight: 1.12,
      fontWeight: '800',
      textAlign: 'center',
      textColor: '#f6fbff',
      backgroundColor: 'rgba(16, 24, 32, 0.82)',
      borderColor: 'rgba(220, 227, 234, 0.78)',
      borderWidth: 3,
      borderRadius: 12,
    } ),
  } ),
  detail: Object.freeze( {
    width: 0.64,
    height: 0.36,
    position: Object.freeze( [ 0.86, 0.42, 0.02 ] ),
    backgroundColor: 0x0d1722,
    backgroundOpacity: 0.9,
    borderColor: 0xffd58f,
  } ),
  desktopPanel: Object.freeze( {
    root: 'font-family: system-ui, sans-serif; color: #eef6ff; width: min(360px, 88vw);',
    title: 'margin: 0 0 8px; font-size: 18px; font-weight: 800;',
    body: 'margin: 0 0 10px; font-size: 13px; line-height: 1.35; white-space: pre-wrap;',
    row: 'display: flex; flex-wrap: wrap; gap: 6px; margin: 8px 0;',
    button: 'border: 1px solid rgba(150, 220, 230, 0.46); border-radius: 8px; background: rgba(24, 48, 64, 0.92); color: #f6fbff; padding: 6px 8px; font-size: 12px; font-weight: 700; cursor: pointer;',
    activeButton: 'border: 1px solid rgba(255, 213, 143, 0.9); border-radius: 8px; background: rgba(66, 82, 56, 0.98); color: #ffffff; padding: 6px 8px; font-size: 12px; font-weight: 800; cursor: pointer;',
    detail: 'margin: 8px 0 0; padding: 8px; border-radius: 8px; background: rgba(8, 16, 24, 0.72); font-size: 12px; line-height: 1.35; white-space: pre-wrap;',
  } ),
} );
