export const demo2CountryMetadata = Object.freeze( {
  AFG: Object.freeze( {
    name: 'Afghanistan',
    lat: 34.5553,
    lon: 69.2075,
    region: 'South Asia',
  } ),
  AUS: Object.freeze( {
    name: 'Australia',
    lat: - 35.2809,
    lon: 149.13,
    region: 'Oceania',
  } ),
  AUT: Object.freeze( {
    name: 'Austria',
    lat: 48.2082,
    lon: 16.3738,
    region: 'Europe',
  } ),
  BEL: Object.freeze( {
    name: 'Belgium',
    lat: 50.8503,
    lon: 4.3517,
    region: 'Europe',
  } ),
  CAN: Object.freeze( {
    name: 'Canada',
    lat: 45.4215,
    lon: - 75.6972,
    region: 'North America',
  } ),
  DEU: Object.freeze( {
    name: 'Germany',
    lat: 52.52,
    lon: 13.405,
    region: 'Europe',
  } ),
  FRA: Object.freeze( {
    name: 'France',
    lat: 48.8566,
    lon: 2.3522,
    region: 'Europe',
  } ),
  GBR: Object.freeze( {
    name: 'United Kingdom',
    lat: 51.5074,
    lon: - 0.1278,
    region: 'Europe',
  } ),
  GRC: Object.freeze( {
    name: 'Greece',
    lat: 37.9838,
    lon: 23.7275,
    region: 'Europe',
  } ),
  IND: Object.freeze( {
    name: 'India',
    lat: 28.6139,
    lon: 77.209,
    region: 'South Asia',
  } ),
  IRN: Object.freeze( {
    name: 'Iran',
    lat: 35.6892,
    lon: 51.389,
    region: 'Middle East',
  } ),
  NLD: Object.freeze( {
    name: 'Netherlands',
    lat: 52.3676,
    lon: 4.9041,
    region: 'Europe',
  } ),
  PAK: Object.freeze( {
    name: 'Pakistan',
    lat: 33.6844,
    lon: 73.0479,
    region: 'South Asia',
  } ),
  SAU: Object.freeze( {
    name: 'Saudi Arabia',
    lat: 24.7136,
    lon: 46.6753,
    region: 'Middle East',
  } ),
  SWE: Object.freeze( {
    name: 'Sweden',
    lat: 59.3293,
    lon: 18.0686,
    region: 'Europe',
  } ),
  TJK: Object.freeze( {
    name: 'Tajikistan',
    lat: 38.5598,
    lon: 68.787,
    region: 'Central Asia',
  } ),
  TUR: Object.freeze( {
    name: 'Turkey',
    lat: 39.9334,
    lon: 32.8597,
    region: 'Middle East',
  } ),
  USA: Object.freeze( {
    name: 'United States',
    lat: 38.9072,
    lon: - 77.0369,
    region: 'North America',
  } ),
} );
